// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infra

import (
	"github.com/google/wire"
	"github.com/longsolong/flow/pkg/setting"
	"sync"
)

// Injectors from wire.go:

// InitializeLogger ...
func InitializeLogger() *Logger {
	appConfig := setting.ProvideAppConfig()
	infraLogger := ProvideLogger(appConfig)
	return infraLogger
}

// wire.go:

var logger *Logger

var once sync.Once

var sentry_once sync.Once

// ProvideLogger ...
func ProvideLogger(appConfig *setting.AppConfig) *Logger {
	once.Do(func() {
		logger = MustNewLogger(appConfig)
	})
	return logger
}

// ProvideLoggerSuperSet ...
var ProvideLoggerSuperSet = wire.NewSet(
	ProvideLogger, setting.DefaultSuperSet,
)
