// Code generated by genaccessor; DO NOT EDIT.

package numberguess

// GetHigh returns the High field.
func (n *numberGuessParam) GetHigh() int {
	return n.High
}

// MustSetHigh set the High field.
func (n *numberGuessParam) MustSetHigh(High int) {
	n.High = High
}

// GetLow returns the Low field.
func (n *numberGuessParam) GetLow() int {
	return n.Low
}

// MustSetLow set the Low field.
func (n *numberGuessParam) MustSetLow(Low int) {
	n.Low = Low
}

// GetSecret returns the Secret field.
func (n *numberGuessParam) GetSecret() int {
	return n.Secret
}

// MustSetSecret set the Secret field.
func (n *numberGuessParam) MustSetSecret(Secret int) {
	n.Secret = Secret
}
