// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package route

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeRoutes
func InitializeRoutes(Gin *gin.Engine) Routes {
	healthCheckRoute := ProvideHealthCheckRoute(Gin)
	apiv1RouterGroup := ProvideAPIV1RouterGroup(Gin)
	routes := Routes{
		HealthCheckRoute: healthCheckRoute,
		APIV1RouterGroup: apiv1RouterGroup,
	}
	return routes
}

// wire.go:

// ProvideHealthCheckRoute ...
func ProvideHealthCheckRoute(Gin *gin.Engine) HealthCheckRoute {
	return HealthCheckRoute{
		Gin: Gin,
	}
}

// ProvideAPIV1RouterGroup ...
func ProvideAPIV1RouterGroup(Gin *gin.Engine) APIV1RouterGroup {
	return APIV1RouterGroup{
		Gin: Gin,
	}
}

var Set = wire.NewSet(
	ProvideHealthCheckRoute,
	ProvideAPIV1RouterGroup, wire.Struct(new(Routes), "HealthCheckRoute", "APIV1RouterGroup"))
