// Code generated by genaccessor; DO NOT EDIT.

package primesieve

// GetInCh returns the InCh field.
func (f *filterParam) GetInCh() <-chan int {
	return f.InCh
}

// MustSetInCh set the InCh field.
func (f *filterParam) MustSetInCh(InCh <-chan int) {
	f.InCh = InCh
}

// GetOutCh returns the OutCh field.
func (f *filterParam) GetOutCh() chan<- int {
	return f.OutCh
}

// MustSetOutCh set the OutCh field.
func (f *filterParam) MustSetOutCh(OutCh chan<- int) {
	f.OutCh = OutCh
}

// GetPrime returns the Prime field.
func (f *filterParam) GetPrime() int {
	return f.Prime
}

// MustSetPrime set the Prime field.
func (f *filterParam) MustSetPrime(Prime int) {
	f.Prime = Prime
}

// GetSeqCh returns the SeqCh field.
func (g *generateParam) GetSeqCh() chan<- int {
	return g.SeqCh
}

// MustSetSeqCh set the SeqCh field.
func (g *generateParam) MustSetSeqCh(SeqCh chan<- int) {
	g.SeqCh = SeqCh
}
